notifications:
  webhooks:
  - https://webhooks.datocms.com/058c8a84fefc28b8d2fc/deploy-results
language: ruby
cache: bundler
rvm:
- 2.4.0
deploy:
  - provider: script
    script: deploy.sh staging
    on:
      branch: staging
  - provider: script
    script: deploy.sh production
    on:
      branch: master
