language: ruby
rvm:
  - 2.4.0
cache: bundler
branches:
  only:
  - master
  - staging
before_script: ruby --version
deploy:
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do ./deploy.sh
  on:
    branch: staging
