source 'http://rubygems.org'

gem 'dotenv'
gem 'middleman-compass'
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-s3_sync'
gem 'middleman-search_engine_sitemap'
gem 'mime-types'
gem 'slim'
